### ISSUE TITLE
Deploy uPort contracts

### ISSUE THREAD

**Issue by ajunge** [uport-project/lambda-olorun#4]
Allow to install the uport contracts in the private chain, using uport-js-client

**Comment by oed** [comment]
This should be fairly simple to do with [uport-js-client](https://github.com/uport-project/uport-js-client)

**Comment by ajunge** [comment]
If it's easly done with uport-js-client then we need to write a step by step guide on how to do it. Also it would be nice for an automatic way to create the https://github.com/uport-project/lambda-olorun/blob/master/src/lib/private-uport-contracts.js file
